export interface Country {
    name: string
    code: string
    phoneCodes: string[]
    currencies: string[]
    languages: string[]
    timezones: string[]
}

export const countries: Country[] = [
    {
        name: 'Afghanistan',
        code: 'AF',
        phoneCodes: ['+93'],
        currencies: ['AFN'],
        languages: ['en', 'ps'],
        timezones: ['AFG'],
    },
    {
        name: 'Albania',
        code: 'AL',
        phoneCodes: ['+355'],
        currencies: ['ALL'],
        languages: ['sq'],
        timezones: ['ALB'],
    },
    {
        name: 'Algeria',
        code: 'DZ',
        phoneCodes: ['+213'],
        currencies: ['DZD'],
        languages: ['ar'],
        timezones: ['DZA'],
    },
    {
        name: 'Andorra',
        code: 'AD',
        phoneCodes: ['+376'],
        currencies: ['EUR'],
        languages: ['ca'],
        timezones: ['AND'],
    },
    {
        name: 'Angola',
        code: 'AO',
        phoneCodes: ['+244'],
        currencies: ['AOA'],
        languages: ['pt'],
        timezones: ['AGO'],
    },
    {
        name: 'Antigua and Barbuda',
        code: 'AG',
        phoneCodes: ['+1268'],
        currencies: ['XCD'],
        languages: ['en'],
        timezones: ['ATG'],
    },
    {
        name: 'Argentina',
        code: 'AR',
        phoneCodes: ['+54'],
        currencies: ['ARS'],
        languages: ['es'],
        timezones: ['ARG'],
    },
    {
        name: 'Armenia',
        code: 'AM',
        phoneCodes: ['+374'],
        currencies: ['AMD'],
        languages: ['hy'],
        timezones: ['ARM'],
    },
    {
        name: 'Australia',
        code: 'AU',
        phoneCodes: ['+61'],
        currencies: ['AUD'],
        languages: ['en'],
        timezones: ['AUS'],
    },
    {
        name: 'Austria',
        code: 'AT',
        phoneCodes: ['+43'],
        currencies: ['EUR'],
        languages: ['de'],
        timezones: ['AUT'],
    },
    {
        name: 'Azerbaijan',
        code: 'AZ',
        phoneCodes: ['+994'],
        currencies: ['AZN'],
        languages: ['az'],
        timezones: ['AZE'],
    },
    {
        name: 'Bahamas',
        code: 'BS',
        phoneCodes: ['+1'],
        currencies: ['BSD'],
        languages: ['en'],
        timezones: ['BHS'],
    },
    {
        name: 'Bahrain',
        code: 'BH',
        phoneCodes: ['+973'],
        currencies: ['BHD'],
        languages: ['ar'],
        timezones: ['BHR'],
    },
    {
        name: 'Bangladesh',
        code: 'BD',
        phoneCodes: ['+880'],
        currencies: ['BDT'],
        languages: ['bn'],
        timezones: ['BGD'],
    },
    {
        name: 'Barbados',
        code: 'BB',
        phoneCodes: ['+1246'],
        currencies: ['BBD'],
        languages: ['en'],
        timezones: ['BRB'],
    },
    {
        name: 'Belarus',
        code: 'BY',
        phoneCodes: ['+375'],
        currencies: ['BYN'],
        languages: ['be', 'ru'],
        timezones: ['BLR'],
    },
    {
        name: 'Belgium',
        code: 'BE',
        phoneCodes: ['+32'],
        currencies: ['EUR'],
        languages: ['nl', 'fr', 'de'],
        timezones: ['BEL'],
    },
    {
        name: 'Belize',
        code: 'BZ',
        phoneCodes: ['+501'],
        currencies: ['BZD'],
        languages: ['en'],
        timezones: ['BLZ'],
    },
    {
        name: 'Benin',
        code: 'BJ',
        phoneCodes: ['+229'],
        currencies: ['XOF'],
        languages: ['fr'],
        timezones: ['BEN'],
    },
    {
        name: 'Bhutan',
        code: 'BT',
        phoneCodes: ['+975'],
        currencies: ['BTN'],
        languages: ['dz'],
        timezones: ['BTN'],
    },
    {
        name: 'Bolivia',
        code: 'BO',
        phoneCodes: ['+591'],
        currencies: ['BOB'],
        languages: ['es', 'qu'],
        timezones: ['BOL'],
    },
    {
        name: 'Bosnia and Herzegovina',
        code: 'BA',
        phoneCodes: ['+387'],
        currencies: ['BAM'],
        languages: ['bs', 'hr', 'sr'],
        timezones: ['BIH'],
    },
    {
        name: 'Botswana',
        code: 'BW',
        phoneCodes: ['+267'],
        currencies: ['BWP'],
        languages: ['en', 'tn'],
        timezones: ['BWA'],
    },
    {
        name: 'Brazil',
        code: 'BR',
        phoneCodes: ['+55'],
        currencies: ['BRL'],
        languages: ['pt'],
        timezones: ['BRA'],
    },
    {
        name: 'Brunei',
        code: 'BN',
        phoneCodes: ['+673'],
        currencies: ['BND'],
        languages: ['ms'],
        timezones: ['BRU'],
    },
    {
        name: 'Bulgaria',
        code: 'BG',
        phoneCodes: ['+359'],
        currencies: ['BGN'],
        languages: ['bg'],
        timezones: ['BGR'],
    },
    {
        name: 'Burkina Faso',
        code: 'BF',
        phoneCodes: ['+226'],
        currencies: ['XOF'],
        languages: ['fr', 'mos'],
        timezones: ['BFA'],
    },
    {
        name: 'Burundi',
        code: 'BI',
        phoneCodes: ['+257'],
        currencies: ['BIF'],
        languages: ['fr', 'rn'],
        timezones: ['BDI'],
    },
    {
        name: 'Cambodia',
        code: 'KH',
        phoneCodes: ['+855'],
        currencies: ['KHR'],
        languages: ['km'],
        timezones: ['ICT'],
    },
    {
        name: 'Cameroon',
        code: 'CM',
        phoneCodes: ['+237'],
        currencies: ['XAF'],
        languages: ['fr', 'en'],
        timezones: ['WAT'],
    },
    {
        name: 'Canada',
        code: 'CA',
        phoneCodes: ['+1'],
        currencies: ['CAD'],
        languages: ['en', 'fr'],
        timezones: ['PST', 'MST', 'CST', 'EST', 'AST'],
    },
    {
        name: 'Cape Verde',
        code: 'CV',
        phoneCodes: ['+238'],
        currencies: ['CVE'],
        languages: ['pt'],
        timezones: ['CVT'],
    },
    {
        name: 'Central African Republic',
        code: 'CF',
        phoneCodes: ['+236'],
        currencies: ['XAF'],
        languages: ['fr', 'sg'],
        timezones: ['WAT'],
    },
    {
        name: 'Chad',
        code: 'TD',
        phoneCodes: ['+235'],
        currencies: ['XAF'],
        languages: ['fr', 'ar'],
        timezones: ['WAT'],
    },
    {
        name: 'Chile',
        code: 'CL',
        phoneCodes: ['+56'],
        currencies: ['CLP'],
        languages: ['es'],
        timezones: ['CLT'],
    },
    {
        name: 'China',
        code: 'CN',
        phoneCodes: ['+86'],
        currencies: ['CNY'],
        languages: ['zh'],
        timezones: ['CST'],
    },
    {
        name: 'Colombia',
        code: 'CO',
        phoneCodes: ['+57'],
        currencies: ['COP'],
        languages: ['es'],
        timezones: ['COT'],
    },
    {
        name: 'Comoros',
        code: 'KM',
        phoneCodes: ['+269'],
        currencies: ['KMF'],
        languages: ['ar', 'fr'],
        timezones: ['EAT'],
    },
    {
        name: 'Congo (Brazzaville)',
        code: 'CG',
        phoneCodes: ['+242'],
        currencies: ['XAF'],
        languages: ['fr'],
        timezones: ['WAT'],
    },
    {
        name: 'Congo (Kinshasa)',
        code: 'CD',
        phoneCodes: ['+243'],
        currencies: ['CDF'],
        languages: ['fr', 'ln', 'kg', 'sw', 'luo'],
        timezones: ['CAT'],
    },
    {
        name: 'Costa Rica',
        code: 'CR',
        phoneCodes: ['+506'],
        currencies: ['CRC'],
        languages: ['es'],
        timezones: ['CST'],
    },
    {
        name: "Cote d'Ivoire",
        code: 'CI',
        phoneCodes: ['+225'],
        currencies: ['XOF'],
        languages: ['fr'],
        timezones: ['GMT'],
    },
    {
        name: 'Croatia',
        code: 'HR',
        phoneCodes: ['+385'],
        currencies: ['HRK'],
        languages: ['hr'],
        timezones: ['CET'],
    },
    {
        name: 'Cuba',
        code: 'CU',
        phoneCodes: ['+53'],
        currencies: ['CUP', 'CUC'],
        languages: ['es'],
        timezones: ['CST'],
    },
    {
        name: 'Cyprus',
        code: 'CY',
        phoneCodes: ['+357'],
        currencies: ['EUR'],
        languages: ['el', 'tr'],
        timezones: ['EET'],
    },
    {
        name: 'Czech Republic',
        code: 'CZ',
        phoneCodes: ['+420'],
        currencies: ['CZK'],
        languages: ['cs'],
        timezones: ['CET'],
    },
    {
        name: 'Denmark',
        code: 'DK',
        phoneCodes: ['+45'],
        currencies: ['DKK'],
        languages: ['da'],
        timezones: ['CET'],
    },
    {
        name: 'Djibouti',
        code: 'DJ',
        phoneCodes: ['+253'],
        currencies: ['DJF'],
        languages: ['fr', 'ar'],
        timezones: ['EAT'],
    },
    {
        name: 'Dominica',
        code: 'DM',
        phoneCodes: ['+1767'],
        currencies: ['XCD'],
        languages: ['en'],
        timezones: ['AST'],
    },
    {
        name: 'Dominican Republic',
        code: 'DO',
        phoneCodes: ['+1'],
        currencies: ['DOP'],
        languages: ['es'],
        timezones: ['AST'],
    },
    {
        name: 'East Timor',
        code: 'TL',
        phoneCodes: ['+670'],
        currencies: ['USD'],
        languages: ['pt'],
        timezones: ['TLT'],
    },
    {
        name: 'Ecuador',
        code: 'EC',
        phoneCodes: ['+593'],
        currencies: ['USD'],
        languages: ['es'],
        timezones: ['ECT'],
    },
    {
        name: 'Egypt',
        code: 'EG',
        phoneCodes: ['+20'],
        currencies: ['EGP'],
        languages: ['ar'],
        timezones: ['EET'],
    },
    {
        name: 'El Salvador',
        code: 'SV',
        phoneCodes: ['+503'],
        currencies: ['USD'],
        languages: ['es'],
        timezones: ['CST'],
    },
    {
        name: 'Equatorial Guinea',
        code: 'GQ',
        phoneCodes: ['+240'],
        currencies: ['XAF'],
        languages: ['es', 'fr'],
        timezones: ['WAT'],
    },
    {
        name: 'Eritrea',
        code: 'ER',
        phoneCodes: ['+291'],
        currencies: ['ERN'],
        languages: ['ti', 'ar', 'en'],
        timezones: ['EAT'],
    },
    {
        name: 'Estonia',
        code: 'EE',
        phoneCodes: ['+372'],
        currencies: ['EUR'],
        languages: ['et'],
        timezones: ['EET'],
    },
    {
        name: 'Eswatini',
        code: 'SZ',
        phoneCodes: ['+268'],
        currencies: ['SZL'],
        languages: ['en', 'ss'],
        timezones: ['SAST'],
    },
    {
        name: 'Ethiopia',
        code: 'ET',
        phoneCodes: ['+251'],
        currencies: ['ETB'],
        languages: ['am', 'ge', 'om', 'ti', 'so', 'sid', 'en'],
        timezones: ['EAT'],
    },
    {
        name: 'Fiji',
        code: 'FJ',
        phoneCodes: ['+679'],
        currencies: ['FJD'],
        languages: ['en', 'fj', 'hi', 'ur'],
        timezones: ['FJT'],
    },
    {
        name: 'Finland',
        code: 'FI',
        phoneCodes: ['+358'],
        currencies: ['EUR'],
        languages: ['fi', 'sv'],
        timezones: ['EET'],
    },
    {
        name: 'France',
        code: 'FR',
        phoneCodes: ['+33'],
        currencies: ['EUR'],
        languages: ['fr'],
        timezones: ['CET'],
    },
    {
        name: 'Gabon',
        code: 'GA',
        phoneCodes: ['+241'],
        currencies: ['XAF'],
        languages: ['fr'],
        timezones: ['WAT'],
    },
    {
        name: 'Gambia',
        code: 'GM',
        phoneCodes: ['+220'],
        currencies: ['GMD'],
        languages: ['en'],
        timezones: ['GMT'],
    },
    {
        name: 'Georgia',
        code: 'GE',
        phoneCodes: ['+995'],
        currencies: ['GEL'],
        languages: ['ka'],
        timezones: ['GET'],
    },
    {
        name: 'Germany',
        code: 'DE',
        phoneCodes: ['+49'],
        currencies: ['EUR'],
        languages: ['de'],
        timezones: ['CET'],
    },
    {
        name: 'Ghana',
        code: 'GH',
        phoneCodes: ['+233'],
        currencies: ['GHS'],
        languages: ['en'],
        timezones: ['GMT'],
    },
    {
        name: 'Greece',
        code: 'GR',
        phoneCodes: ['+30'],
        currencies: ['EUR'],
        languages: ['el'],
        timezones: ['EET'],
    },
    {
        name: 'Grenada',
        code: 'GD',
        phoneCodes: ['+1473'],
        currencies: ['XCD'],
        languages: ['en'],
        timezones: ['AST'],
    },
    {
        name: 'Guatemala',
        code: 'GT',
        phoneCodes: ['+502'],
        currencies: ['GTQ'],
        languages: ['es'],
        timezones: ['CST'],
    },
    {
        name: 'Guinea',
        code: 'GN',
        phoneCodes: ['+224'],
        currencies: ['GNF'],
        languages: ['fr'],
        timezones: ['GMT'],
    },
    {
        name: 'Guinea-Bissau',
        code: 'GW',
        phoneCodes: ['+245'],
        currencies: ['XOF'],
        languages: ['pt'],
        timezones: ['GMT'],
    },
    {
        name: 'Guyana',
        code: 'GY',
        phoneCodes: ['+592'],
        currencies: ['GYD'],
        languages: ['en'],
        timezones: ['GYT'],
    },
    {
        name: 'Haiti',
        code: 'HT',
        phoneCodes: ['+509'],
        currencies: ['HTG', 'USD'],
        languages: ['fr', 'ht'],
        timezones: ['EST'],
    },
    {
        name: 'Honduras',
        code: 'HN',
        phoneCodes: ['+504'],
        currencies: ['HNL'],
        languages: ['es'],
        timezones: ['CST'],
    },
    {
        name: 'Hungary',
        code: 'HU',
        phoneCodes: ['+36'],
        currencies: ['HUF'],
        languages: ['hu'],
        timezones: ['CET'],
    },
    {
        name: 'Iceland',
        code: 'IS',
        phoneCodes: ['+354'],
        currencies: ['ISK'],
        languages: ['is'],
        timezones: ['GMT'],
    },
    {
        name: 'India',
        code: 'IN',
        phoneCodes: ['+91'],
        currencies: ['INR'],
        languages: ['en', 'hi'],
        timezones: ['IST'],
    },
    {
        name: 'Indonesia',
        code: 'ID',
        phoneCodes: ['+62'],
        currencies: ['IDR'],
        languages: ['id'],
        timezones: ['WIT', 'CIT', 'EIT'],
    },
    {
        name: 'Iran',
        code: 'IR',
        phoneCodes: ['+98'],
        currencies: ['IRR'],
        languages: ['fa'],
        timezones: ['IRST'],
    },
    {
        name: 'Iraq',
        code: 'IQ',
        phoneCodes: ['+964'],
        currencies: ['IQD'],
        languages: ['ar'],
        timezones: ['AST'],
    },
    {
        name: 'Ireland',
        code: 'IE',
        phoneCodes: ['+353'],
        currencies: ['EUR'],
        languages: ['ga', 'en'],
        timezones: ['GMT'],
    },
    {
        name: 'Israel',
        code: 'IL',
        phoneCodes: ['+972'],
        currencies: ['ILS'],
        languages: ['he', 'ar'],
        timezones: ['IST'],
    },
    {
        name: 'Italy',
        code: 'IT',
        phoneCodes: ['+39'],
        currencies: ['EUR'],
        languages: ['it'],
        timezones: ['CET'],
    },
    {
        name: 'Jamaica',
        code: 'JM',
        phoneCodes: ['+1876'],
        currencies: ['JMD'],
        languages: ['en'],
        timezones: ['EST'],
    },
    {
        name: 'Japan',
        code: 'JP',
        phoneCodes: ['+81'],
        currencies: ['JPY'],
        languages: ['ja'],
        timezones: ['JST'],
    },
    {
        name: 'Jordan',
        code: 'JO',
        phoneCodes: ['+962'],
        currencies: ['JOD'],
        languages: ['ar'],
        timezones: ['EET'],
    },
    {
        name: 'Kazakhstan',
        code: 'KZ',
        phoneCodes: ['+7'],
        currencies: ['KZT'],
        languages: ['kk', 'ru'],
        timezones: ['ALMT'],
    },
    {
        name: 'Kenya',
        code: 'KE',
        phoneCodes: ['+254'],
        currencies: ['KES'],
        languages: ['en', 'sw'],
        timezones: ['EAT'],
    },
    {
        name: 'Kiribati',
        code: 'KI',
        phoneCodes: ['+686'],
        currencies: ['AUD'],
        languages: ['en', 'gil'],
        timezones: ['GILT'],
    },
    {
        name: 'Korea, North',
        code: 'KP',
        phoneCodes: ['+850'],
        currencies: ['KPW'],
        languages: ['ko'],
        timezones: ['KST'],
    },
    {
        name: 'Korea, South',
        code: 'KR',
        phoneCodes: ['+82'],
        currencies: ['KRW'],
        languages: ['ko'],
        timezones: ['KST'],
    },
    {
        name: 'Kosovo',
        code: 'XK',
        phoneCodes: ['+383'],
        currencies: ['EUR'],
        languages: ['sq', 'sr'],
        timezones: ['CET'],
    },
    {
        name: 'Kuwait',
        code: 'KW',
        phoneCodes: ['+965'],
        currencies: ['KWD'],
        languages: ['ar'],
        timezones: ['AST'],
    },
    {
        name: 'Kyrgyzstan',
        code: 'KG',
        phoneCodes: ['+996'],
        currencies: ['KGS'],
        languages: ['ky', 'ru'],
        timezones: ['KGT'],
    },
    {
        name: 'Laos',
        code: 'LA',
        phoneCodes: ['+856'],
        currencies: ['LAK'],
        languages: ['lo'],
        timezones: ['ICT'],
    },
    {
        name: 'Latvia',
        code: 'LV',
        phoneCodes: ['+371'],
        currencies: ['EUR'],
        languages: ['lv'],
        timezones: ['EET'],
    },
    {
        name: 'Lebanon',
        code: 'LB',
        phoneCodes: ['+961'],
        currencies: ['LBP'],
        languages: ['ar', 'fr', 'en'],
        timezones: ['EET'],
    },
    {
        name: 'Lesotho',
        code: 'LS',
        phoneCodes: ['+266'],
        currencies: ['LSL', 'ZAR'],
        languages: ['en', 'st'],
        timezones: ['SAST'],
    },
    {
        name: 'Liberia',
        code: 'LR',
        phoneCodes: ['+231'],
        currencies: ['LRD'],
        languages: ['en'],
        timezones: ['GMT'],
    },
    {
        name: 'Libya',
        code: 'LY',
        phoneCodes: ['+218'],
        currencies: ['LYD'],
        languages: ['ar'],
        timezones: ['EET'],
    },
    {
        name: 'Liechtenstein',
        code: 'LI',
        phoneCodes: ['+423'],
        currencies: ['CHF', 'EUR'],
        languages: ['de'],
        timezones: ['CET'],
    },
    {
        name: 'Lithuania',
        code: 'LT',
        phoneCodes: ['+370'],
        currencies: ['EUR'],
        languages: ['lt'],
        timezones: ['EET'],
    },
    {
        name: 'Luxembourg',
        code: 'LU',
        phoneCodes: ['+352'],
        currencies: ['EUR'],
        languages: ['lb', 'de', 'fr'],
        timezones: ['CET'],
    },
    {
        name: 'Macedonia',
        code: 'MK',
        phoneCodes: ['+389'],
        currencies: ['MKD'],
        languages: ['mk'],
        timezones: ['CET'],
    },
    {
        name: 'Madagascar',
        code: 'MG',
        phoneCodes: ['+261'],
        currencies: ['MGA'],
        languages: ['fr', 'mg'],
        timezones: ['EAT'],
    },
    {
        name: 'Malawi',
        code: 'MW',
        phoneCodes: ['+265'],
        currencies: ['MWK'],
        languages: ['en', 'ny'],
        timezones: ['CAT'],
    },
    {
        name: 'Malaysia',
        code: 'MY',
        phoneCodes: ['+60'],
        currencies: ['MYR'],
        languages: ['ms'],
        timezones: ['MYT'],
    },
    {
        name: 'Maldives',
        code: 'MV',
        phoneCodes: ['+960'],
        currencies: ['MVR'],
        languages: ['dv'],
        timezones: ['MVT'],
    },
    {
        name: 'Mali',
        code: 'ML',
        phoneCodes: ['+223'],
        currencies: ['XOF'],
        languages: ['fr', 'bm'],
        timezones: ['GMT'],
    },
    {
        name: 'Malta',
        code: 'MT',
        phoneCodes: ['+356'],
        currencies: ['EUR'],
        languages: ['mt', 'en'],
        timezones: ['CET'],
    },
    {
        name: 'Marshall Islands',
        code: 'MH',
        phoneCodes: ['+692'],
        currencies: ['USD'],
        languages: ['mh', 'en'],
        timezones: ['MHT'],
    },
    {
        name: 'Mauritania',
        code: 'MR',
        phoneCodes: ['+222'],
        currencies: ['MRU'],
        languages: ['ar', 'fr'],
        timezones: ['GMT'],
    },
    {
        name: 'Mauritius',
        code: 'MU',
        phoneCodes: ['+230'],
        currencies: ['MUR'],
        languages: ['en', 'fr'],
        timezones: ['MUT'],
    },
    {
        name: 'Mexico',
        code: 'MX',
        phoneCodes: ['+52'],
        currencies: ['MXN'],
        languages: ['es'],
        timezones: ['CST', 'MST', 'PST'],
    },
    {
        name: 'Micronesia',
        code: 'FM',
        phoneCodes: ['+691'],
        currencies: ['USD'],
        languages: ['en'],
        timezones: ['ChST'],
    },
    {
        name: 'Moldova',
        code: 'MD',
        phoneCodes: ['+373'],
        currencies: ['MDL'],
        languages: ['ro'],
        timezones: ['EET'],
    },
    {
        name: 'Monaco',
        code: 'MC',
        phoneCodes: ['+377'],
        currencies: ['EUR'],
        languages: ['fr'],
        timezones: ['CET'],
    },
    {
        name: 'Mongolia',
        code: 'MN',
        phoneCodes: ['+976'],
        currencies: ['MNT'],
        languages: ['mn'],
        timezones: ['ULAT'],
    },
    {
        name: 'Montenegro',
        code: 'ME',
        phoneCodes: ['+382'],
        currencies: ['EUR'],
        languages: ['sr', 'bs', 'hr'],
        timezones: ['CET'],
    },
    {
        name: 'Morocco',
        code: 'MA',
        phoneCodes: ['+212'],
        currencies: ['MAD'],
        languages: ['ar'],
        timezones: ['WET'],
    },
    {
        name: 'Mozambique',
        code: 'MZ',
        phoneCodes: ['+258'],
        currencies: ['MZN'],
        languages: ['pt'],
        timezones: ['CAT'],
    },
    {
        name: 'Myanmar',
        code: 'MM',
        phoneCodes: ['+95'],
        currencies: ['MMK'],
        languages: ['my'],
        timezones: ['MMT'],
    },
    {
        name: 'Namibia',
        code: 'NA',
        phoneCodes: ['+264'],
        currencies: ['NAD', 'ZAR'],
        languages: ['en', 'af', 'de', 'naq'],
        timezones: ['WAT'],
    },
    {
        name: 'Nauru',
        code: 'NR',
        phoneCodes: ['+674'],
        currencies: ['AUD'],
        languages: ['na', 'en'],
        timezones: ['NRT'],
    },
    {
        name: 'Nepal',
        code: 'NP',
        phoneCodes: ['+977'],
        currencies: ['NPR'],
        languages: ['ne'],
        timezones: ['NPT'],
    },
    {
        name: 'Netherlands',
        code: 'NL',
        phoneCodes: ['+31'],
        currencies: ['EUR'],
        languages: ['nl'],
        timezones: ['CET'],
    },
    {
        name: 'New Zealand',
        code: 'NZ',
        phoneCodes: ['+64'],
        currencies: ['NZD'],
        languages: ['en', 'mi'],
        timezones: ['NZST'],
    },
    {
        name: 'Nicaragua',
        code: 'NI',
        phoneCodes: ['+505'],
        currencies: ['NIO'],
        languages: ['es'],
        timezones: ['CST'],
    },
    {
        name: 'Niger',
        code: 'NE',
        phoneCodes: ['+227'],
        currencies: ['XOF'],
        languages: ['fr'],
        timezones: ['WAT'],
    },
    {
        name: 'Nigeria',
        code: 'NG',
        phoneCodes: ['+234'],
        currencies: ['NGN'],
        languages: ['en'],
        timezones: ['WAT'],
    },
    {
        name: 'North Macedonia',
        code: 'MK',
        phoneCodes: ['+389'],
        currencies: ['MKD'],
        languages: ['mk'],
        timezones: ['CET'],
    },
    {
        name: 'Norway',
        code: 'NO',
        phoneCodes: ['+47'],
        currencies: ['NOK'],
        languages: ['no'],
        timezones: ['CET'],
    },
    {
        name: 'Oman',
        code: 'OM',
        phoneCodes: ['+968'],
        currencies: ['OMR'],
        languages: ['ar'],
        timezones: ['GST'],
    },
    {
        name: 'Pakistan',
        code: 'PK',
        phoneCodes: ['+92'],
        currencies: ['PKR'],
        languages: ['ur', 'en'],
        timezones: ['PKT'],
    },
    {
        name: 'Palau',
        code: 'PW',
        phoneCodes: ['+680'],
        currencies: ['USD'],
        languages: ['en'],
        timezones: ['PWT'],
    },
    {
        name: 'Palestine',
        code: 'PS',
        phoneCodes: ['+970'],
        currencies: ['ILS'],
        languages: ['ar'],
        timezones: ['EET'],
    },
    {
        name: 'Panama',
        code: 'PA',
        phoneCodes: ['+507'],
        currencies: ['PAB', 'USD'],
        languages: ['es'],
        timezones: ['EST'],
    },
    {
        name: 'Papua New Guinea',
        code: 'PG',
        phoneCodes: ['+675'],
        currencies: ['PGK'],
        languages: ['en', 'ho', 'tpi'],
        timezones: ['PGT'],
    },
    {
        name: 'Paraguay',
        code: 'PY',
        phoneCodes: ['+595'],
        currencies: ['PYG'],
        languages: ['es', 'gn'],
        timezones: ['PYT'],
    },
    {
        name: 'Peru',
        code: 'PE',
        phoneCodes: ['+51'],
        currencies: ['PEN'],
        languages: ['es', 'qu'],
        timezones: ['PET'],
    },
    {
        name: 'Philippines',
        code: 'PH',
        phoneCodes: ['+63'],
        currencies: ['PHP'],
        languages: ['en', 'tl'],
        timezones: ['PHT'],
    },
    {
        name: 'Poland',
        code: 'PL',
        phoneCodes: ['+48'],
        currencies: ['PLN'],
        languages: ['pl'],
        timezones: ['CET'],
    },
    {
        name: 'Portugal',
        code: 'PT',
        phoneCodes: ['+351'],
        currencies: ['EUR'],
        languages: ['pt'],
        timezones: ['WET'],
    },
    {
        name: 'Qatar',
        code: 'QA',
        phoneCodes: ['+974'],
        currencies: ['QAR'],
        languages: ['ar'],
        timezones: ['AST'],
    },
    {
        name: 'Romania',
        code: 'RO',
        phoneCodes: ['+40'],
        currencies: ['RON'],
        languages: ['ro'],
        timezones: ['EET'],
    },
    {
        name: 'Russia',
        code: 'RU',
        phoneCodes: ['+7'],
        currencies: ['RUB'],
        languages: ['ru'],
        timezones: ['MSK', 'SAMT', 'YEKT', 'OMST', 'KRAT', 'IRKT', 'YAKT', 'VLAT'],
    },
    {
        name: 'Rwanda',
        code: 'RW',
        phoneCodes: ['+250'],
        currencies: ['RWF'],
        languages: ['rw', 'en', 'fr'],
        timezones: ['CAT'],
    },
    {
        name: 'Saint Kitts and Nevis',
        code: 'KN',
        phoneCodes: ['+1869'],
        currencies: ['XCD'],
        languages: ['en'],
        timezones: ['AST'],
    },
    {
        name: 'Saint Lucia',
        code: 'LC',
        phoneCodes: ['+1758'],
        currencies: ['XCD'],
        languages: ['en'],
        timezones: ['AST'],
    },
    {
        name: 'Saint Vincent and the Grenadines',
        code: 'VC',
        phoneCodes: ['+1784'],
        currencies: ['XCD'],
        languages: ['en'],
        timezones: ['AST'],
    },
    {
        name: 'Samoa',
        code: 'WS',
        phoneCodes: ['+685'],
        currencies: ['WST'],
        languages: ['sm', 'en'],
        timezones: ['WST'],
    },
    {
        name: 'San Marino',
        code: 'SM',
        phoneCodes: ['+378'],
        currencies: ['EUR'],
        languages: ['it'],
        timezones: ['CET'],
    },
    {
        name: 'Sao Tome and Principe',
        code: 'ST',
        phoneCodes: ['+239'],
        currencies: ['STN'],
        languages: ['pt'],
        timezones: ['GMT'],
    },
    {
        name: 'Saudi Arabia',
        code: 'SA',
        phoneCodes: ['+966'],
        currencies: ['SAR'],
        languages: ['ar'],
        timezones: ['AST'],
    },
    {
        name: 'Senegal',
        code: 'SN',
        phoneCodes: ['+221'],
        currencies: ['XOF'],
        languages: ['fr'],
        timezones: ['GMT'],
    },
    {
        name: 'Serbia',
        code: 'RS',
        phoneCodes: ['+381'],
        currencies: ['RSD'],
        languages: ['sr'],
        timezones: ['CET'],
    },
    {
        name: 'Seychelles',
        code: 'SC',
        phoneCodes: ['+248'],
        currencies: ['SCR'],
        languages: ['en', 'fr'],
        timezones: ['SCT'],
    },
    {
        name: 'Sierra Leone',
        code: 'SL',
        phoneCodes: ['+232'],
        currencies: ['SLL'],
        languages: ['en'],
        timezones: ['GMT'],
    },
    {
        name: 'Singapore',
        code: 'SG',
        phoneCodes: ['+65'],
        currencies: ['SGD'],
        languages: ['en', 'ms', 'ta', 'zh'],
        timezones: ['SGT'],
    },
    {
        name: 'Slovakia',
        code: 'SK',
        phoneCodes: ['+421'],
        currencies: ['EUR'],
        languages: ['sk'],
        timezones: ['CET'],
    },
    {
        name: 'Slovenia',
        code: 'SI',
        phoneCodes: ['+386'],
        currencies: ['EUR'],
        languages: ['sl'],
        timezones: ['CET'],
    },
    {
        name: 'Solomon Islands',
        code: 'SB',
        phoneCodes: ['+677'],
        currencies: ['SBD'],
        languages: ['en'],
        timezones: ['SBT'],
    },
    {
        name: 'Somalia',
        code: 'SO',
        phoneCodes: ['+252'],
        currencies: ['SOS'],
        languages: ['so', 'ar'],
        timezones: ['EAT'],
    },
    {
        name: 'South Africa',
        code: 'ZA',
        phoneCodes: ['+27'],
        currencies: ['ZAR'],
        languages: ['zu', 'xh', 'af', 'en', 'tn', 'st', 'ts', 'ss', 've', 'nr'],
        timezones: ['SAST'],
    },
    {
        name: 'South Sudan',
        code: 'SS',
        phoneCodes: ['+211'],
        currencies: ['SSP'],
        languages: ['en'],
        timezones: ['EAT'],
    },
    {
        name: 'Spain',
        code: 'ES',
        phoneCodes: ['+34'],
        currencies: ['EUR'],
        languages: ['es', 'ca', 'gl', 'eu'],
        timezones: ['CET'],
    },
    {
        name: 'Sri Lanka',
        code: 'LK',
        phoneCodes: ['+94'],
        currencies: ['LKR'],
        languages: ['si', 'ta'],
        timezones: ['IST'],
    },
    {
        name: 'Sudan',
        code: 'SD',
        phoneCodes: ['+249'],
        currencies: ['SDG'],
        languages: ['ar', 'en'],
        timezones: ['EAT'],
    },
    {
        name: 'Suriname',
        code: 'SR',
        phoneCodes: ['+597'],
        currencies: ['SRD'],
        languages: ['nl'],
        timezones: ['SRT'],
    },
    {
        name: 'Sweden',
        code: 'SE',
        phoneCodes: ['+46'],
        currencies: ['SEK'],
        languages: ['sv'],
        timezones: ['CET'],
    },
    {
        name: 'Switzerland',
        code: 'CH',
        phoneCodes: ['+41'],
        currencies: ['CHF'],
        languages: ['de', 'fr', 'it', 'rm'],
        timezones: ['CET'],
    },
    {
        name: 'Syria',
        code: 'SY',
        phoneCodes: ['+963'],
        currencies: ['SYP'],
        languages: ['ar'],
        timezones: ['EET'],
    },
    {
        name: 'Taiwan',
        code: 'TW',
        phoneCodes: ['+886'],
        currencies: ['TWD'],
        languages: ['zh'],
        timezones: ['CST'],
    },
    {
        name: 'Tajikistan',
        code: 'TJ',
        phoneCodes: ['+992'],
        currencies: ['TJS'],
        languages: ['tg'],
        timezones: ['TJT'],
    },
    {
        name: 'Tanzania',
        code: 'TZ',
        phoneCodes: ['+255'],
        currencies: ['TZS'],
        languages: ['sw', 'en'],
        timezones: ['EAT'],
    },
    {
        name: 'Thailand',
        code: 'TH',
        phoneCodes: ['+66'],
        currencies: ['THB'],
        languages: ['th'],
        timezones: ['ICT'],
    },
    {
        name: 'Togo',
        code: 'TG',
        phoneCodes: ['+228'],
        currencies: ['XOF'],
        languages: ['fr'],
        timezones: ['GMT'],
    },
    {
        name: 'Tonga',
        code: 'TO',
        phoneCodes: ['+676'],
        currencies: ['TOP'],
        languages: ['en', 'to'],
        timezones: ['TOT'],
    },
    {
        name: 'Trinidad and Tobago',
        code: 'TT',
        phoneCodes: ['+1868'],
        currencies: ['TTD'],
        languages: ['en'],
        timezones: ['AST'],
    },
    {
        name: 'Tunisia',
        code: 'TN',
        phoneCodes: ['+216'],
        currencies: ['TND'],
        languages: ['ar', 'fr'],
        timezones: ['CET'],
    },
    {
        name: 'Turkey',
        code: 'TR',
        phoneCodes: ['+90'],
        currencies: ['TRY'],
        languages: ['tr'],
        timezones: ['TRT'],
    },
    {
        name: 'Turkmenistan',
        code: 'TM',
        phoneCodes: ['+993'],
        currencies: ['TMT'],
        languages: ['tk', 'ru'],
        timezones: ['TMT'],
    },
    {
        name: 'Tuvalu',
        code: 'TV',
        phoneCodes: ['+688'],
        currencies: ['AUD'],
        languages: ['tvl', 'en'],
        timezones: ['TVT'],
    },
    {
        name: 'Uganda',
        code: 'UG',
        phoneCodes: ['+256'],
        currencies: ['UGX'],
        languages: ['en', 'sw'],
        timezones: ['EAT'],
    },
    {
        name: 'Ukraine',
        code: 'UA',
        phoneCodes: ['+380'],
        currencies: ['UAH'],
        languages: ['uk'],
        timezones: ['EET'],
    },
    {
        name: 'United Arab Emirates',
        code: 'AE',
        phoneCodes: ['+971'],
        currencies: ['AED'],
        languages: ['ar'],
        timezones: ['GST'],
    },
    {
        name: 'United Kingdom',
        code: 'GB',
        phoneCodes: ['+44'],
        currencies: ['GBP'],
        languages: ['en'],
        timezones: ['GMT'],
    },
    {
        name: 'United States',
        code: 'US',
        phoneCodes: ['+1'],
        currencies: ['USD'],
        languages: ['en'],
        timezones: ['EST', 'CST', 'MST', 'PST', 'AKST', 'HST'],
    },
    {
        name: 'Uruguay',
        code: 'UY',
        phoneCodes: ['+598'],
        currencies: ['UYU'],
        languages: ['es'],
        timezones: ['UYT'],
    },
    {
        name: 'Uzbekistan',
        code: 'UZ',
        phoneCodes: ['+998'],
        currencies: ['UZS'],
        languages: ['uz', 'ka'],
        timezones: ['UZT'],
    },
    {
        name: 'Vanuatu',
        code: 'VU',
        phoneCodes: ['+678'],
        currencies: ['VUV'],
        languages: ['bi', 'en', 'fr'],
        timezones: ['VUT'],
    },
    {
        name: 'Vatican City',
        code: 'VA',
        phoneCodes: ['+39'],
        currencies: ['EUR'],
        languages: ['it', 'la'],
        timezones: ['CET'],
    },
    {
        name: 'Venezuela',
        code: 'VE',
        phoneCodes: ['+58'],
        currencies: ['VES'],
        languages: ['es'],
        timezones: ['VET'],
    },
    {
        name: 'Vietnam',
        code: 'VN',
        phoneCodes: ['+84'],
        currencies: ['VND'],
        languages: ['vi'],
        timezones: ['ICT'],
    },
    {
        name: 'Yemen',
        code: 'YE',
        phoneCodes: ['+967'],
        currencies: ['YER'],
        languages: ['ar'],
        timezones: ['AST'],
    },
    {
        name: 'Zambia',
        code: 'ZM',
        phoneCodes: ['+260'],
        currencies: ['ZMW'],
        languages: ['en'],
        timezones: ['CAT'],
    },
    {
        name: 'Zimbabwe',
        code: 'ZW',
        phoneCodes: ['+263'],
        currencies: ['ZWL'],
        languages: ['en', 'sn', 'nd'],
        timezones: ['CAT'],
    },
];



